targets:
  $default:
    builders:
      riverpod_generator:
        options:
          riverpod_version: "2"
      source_gen:part_builder:
        options:
          build_extensions:
            .dart:
              - .g.dart
