import 'package:stroke_wars/features/canvas/domain/models/drawing_event.dart';
import 'package:stroke_wars/features/match/domain/models/match_snapshot.dart';
import 'package:stroke_wars/features/multiplayer/domain/models/room.dart';

/// Represents a complete snapshot of the multiplayer room, match, and drawing sessions.
class RoomSnapshot {
  const RoomSnapshot({
    required this.snapshotVersion,
    required this.generatedAt,
    required this.sequenceNumber,
    required this.matchSequence,
    required this.room,
    this.matchSnapshot,
    required this.drawingEvents,
    this.replayReference,
  });

  /// Monotonically increasing snapshot schema or data version.
  final int snapshotVersion;

  /// Timestamp of when the snapshot was generated by the Host.
  final DateTime generatedAt;

  /// Envelope sequence number this snapshot corresponds to.
  final int sequenceNumber;

  /// Authoritative match event sequence number.
  final int matchSequence;

  /// Room lobby state.
  final Room room;

  /// Authoritative match state snapshot (if playing).
  final MatchSnapshot? matchSnapshot;

  /// List of active canvas drawing events representing current drawings.
  final List<DrawingEvent> drawingEvents;

  /// Optional replay engine UUID reference.
  final String? replayReference;

  Map<String, dynamic> toJson() => {
        'snapshotVersion': snapshotVersion,
        'generatedAt': generatedAt.toIso8601String(),
        'sequenceNumber': sequenceNumber,
        'matchSequence': matchSequence,
        'room': room.toJson(),
        'matchSnapshot': matchSnapshot?.toJson(),
        'drawingEvents': drawingEvents.map((e) => e.toJson()).toList(),
        'replayReference': replayReference,
      };

  factory RoomSnapshot.fromJson(Map<String, dynamic> json) => RoomSnapshot(
        snapshotVersion: json['snapshotVersion'] as int,
        generatedAt: DateTime.parse(json['generatedAt'] as String),
        sequenceNumber: json['sequenceNumber'] as int,
        matchSequence: json['matchSequence'] as int,
        room: Room.fromJson(json['room'] as Map<String, dynamic>),
        matchSnapshot: json['matchSnapshot'] != null
            ? MatchSnapshot.fromJson(json['matchSnapshot'] as Map<String, dynamic>)
            : null,
        drawingEvents: (json['drawingEvents'] as List<dynamic>)
            .map((e) => DrawingEvent.fromJson(e as Map<String, dynamic>))
            .toList(),
        replayReference: json['replayReference'] as String?,
      );
}
